<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="0"
            failures="1"
            tests="3">

  <testsuite name="auth-flow"
    errors="0" failures="1" hostname="" id="" package="auth-flow" skipped="2"
    tests="3" time="1.759" timestamp="Fri, 28 Jul 2017 17:08:16 GMT">
  
    <testcase name="get to signup page" classname="auth-flow" time="1.759" assertions="2">

      <failure message="Testing if the URL contains &quot;signup&quot;.">    at Object.get to signup page (/Users/Sean/Portfolio/jet-log/client/tests/auth-flow.js:10:19)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)</failure>

    
    </testcase>
  

  

  
    
    <testcase
      name="signup user and redirect to cart" classname="auth-flow">
      <skipped />
    </testcase>
    
    <testcase
      name="close" classname="auth-flow">
      <skipped />
    </testcase>
    
  
  </testsuite>
</testsuites>
